primeiranota = input("Digite a primeira nota: ")
print()
segundanota = input("Digite a segunda nota: ")
print()
terceiranota = input("Digite a terceira nota: ")
print()
quartanota = input("digite a quarta nota: ")
print()
nota1 = float(primeiranota)
nota2 = float(segundanota)
nota3 = float(terceiranota)
nota4 = float(quartanota)

media=((nota1+nota2+nota3+nota4)/4)

print("A média aritmética é",media)